import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STRINGS = {
  en: {
    'admin.abuseEvents': 'Abuse Events',
    'admin.adminOperations': 'Admin Operations',
    'admin.alerts': 'Alerts',
    'admin.failureRate': 'Failure Rate',
    'admin.incidents': 'Incidents',
    'admin.loading': 'Loading admin snapshots...',
    'admin.margin': 'Margin',
    'admin.queue': 'Queue',
    'admin.sessions': 'Sessions',
    'admin.security': 'Security',
    'admin.tokenBurn': 'Token Burn 1h',
    'app.dashboardTitle': 'BuilderBot Dashboard',
    'app.loading': 'Loading...',
    'app.logout': 'Log Out',
    'build.aiPatchPlans': 'AI Patch Plans',
    'build.aiPlans': 'AI Plans',
    'build.attempts': 'Attempts',
    'build.buildHistory': 'Build History',
    'build.loadingBuildDetails': 'Loading build details...',
    'build.loadingBuilds': 'Loading builds...',
    'build.localPlans': 'Local Plans',
    'build.localRatio': 'Local Ratio',
    'build.noBuilds': 'No builds recorded yet.',
    'build.replans': 'Replans',
    'build.selectBuild': 'Select a build to view details.',
    'build.source': 'Source',
    'build.success': 'Success',
    'build.successRate': 'Success Rate',
    'build.totalBuilds': 'Total Builds',
    'build.aiCallsAvoided': 'AI Calls Avoided',
    'common.refresh': 'Refresh',
    'common.unknown': 'Unknown',
    'common.unknownTime': 'Unknown time',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.cancel': 'Cancel',
    'community.community': 'Community',
    'community.entitlements': 'Entitlements',
    'community.linked': 'Linked',
    'community.listings': 'Listings',
    'community.loading': 'Loading community data...',
    'community.createListing': 'Create Listing',
    'community.createPhrasePack': 'Create Phrase Pack',
    'community.description': 'Description',
    'community.listingTitle': 'Listing Title',
    'community.phrasePackName': 'Phrase Pack Name',
    'community.phrasePacks': 'Phrase Packs',
    'community.phrases': 'Phrases',
    'community.priceUsd': 'Price USD',
    'community.redeem': 'Redeem',
    'community.redeemCode': 'Redeem Code',
    'community.referral': 'Referral',
    'community.referralCode': 'Referral Code',
    'community.rewards': 'Rewards',
    'community.save': 'Save',
    'control.status': 'Status',
    'checkout.processing': 'Processing payment...',
    'checkout.redirecting': 'Payment processed! Redirecting...',
    'console.activityEmpty': 'No bot activity yet.',
    'console.blocksNearby': 'Nearby Blocks',
    'console.botPosition': 'Bot position',
    'console.chatControl': 'Enable Chat Control',
    'console.coordinates': 'Enter Coordinates',
    'console.follow': 'Follow',
    'console.go': 'Go',
    'console.inventory': 'Inventory',
    'console.moveTo': 'Move To',
    'console.movingTo': 'Moving to',
    'console.placed': 'Placed',
    'console.reachedGoal': 'Reached goal at',
    'console.stop': 'Stop',
    'launch.botName': 'Bot Name',
    'launch.botNameHelp': 'The name that will appear in-game.',
    'launch.commanderUuid': 'Your Minecraft UUID',
    'launch.commanderUuidHelp': 'The UUID of the player issuing commands.',
    'launch.launch': 'Launch',
    'launch.minecraftIp': 'Minecraft Server IP',
    'launch.minecraftIpHelp': 'Defaults to 127.0.0.1 for local testing.',
    'launch.minecraftPort': 'Minecraft Server Port',
    'launch.minecraftPortHelp': 'Typically 25565 unless changed.',
    'launch.minecraftVersion': 'Minecraft Version',
    'launch.minecraftVersionHelp': 'Ensure it matches your server.',
    'launch.title': 'Launch BuilderBot',
    'plan.acceptPolicies': 'I accept the Terms and Privacy policy',
    'plan.adminDescription': 'Unlimited builds, full access',
    'plan.bestValue': 'Best Value',
    'plan.choosePlan': 'Welcome to BuilderBot! Choose Your Plan',
    'plan.continueFree': 'Continue Free',
    'plan.freeDescription': 'Limited to 50-block builds',
    'plan.policyRequired': 'Please accept Terms and Privacy before choosing a plan.',
    'plan.proDescription': '2,000-block builds + AI chat',
    'plan.starterDescription': '500-block builds + templates',
    'plan.startCheckoutFailed': 'Failed to start checkout.',
    'plan.chooseFailed': 'Failed to choose plan.',
    'plan.upgrade': 'Upgrade',
    'prompt.placeholder': 'Enter command (e.g. build a cube)...',
    'prompt.send': 'Send',
  },
  es: {
    'admin.abuseEvents': 'Eventos de abuso',
    'admin.adminOperations': 'Operaciones admin',
    'admin.alerts': 'Alertas',
    'admin.failureRate': 'Tasa de fallos',
    'admin.incidents': 'Incidentes',
    'admin.loading': 'Cargando datos admin...',
    'admin.margin': 'Margen',
    'admin.queue': 'Cola',
    'admin.sessions': 'Sesiones',
    'admin.security': 'Seguridad',
    'admin.tokenBurn': 'Gasto tokens 1h',
    'app.dashboardTitle': 'Panel BuilderBot',
    'app.loading': 'Cargando...',
    'app.logout': 'Cerrar sesion',
    'build.aiPatchPlans': 'Parches IA',
    'build.aiPlans': 'Planes IA',
    'build.attempts': 'Intentos',
    'build.buildHistory': 'Historial',
    'build.loadingBuildDetails': 'Cargando detalle...',
    'build.loadingBuilds': 'Cargando builds...',
    'build.localPlans': 'Planes locales',
    'build.localRatio': 'Ratio local',
    'build.noBuilds': 'Sin builds registrados.',
    'build.replans': 'Replanes',
    'build.selectBuild': 'Selecciona un build.',
    'build.source': 'Origen',
    'build.success': 'Exito',
    'build.successRate': 'Tasa exito',
    'build.totalBuilds': 'Builds totales',
    'build.aiCallsAvoided': 'IA evitada',
    'common.refresh': 'Actualizar',
    'common.unknown': 'Desconocido',
    'common.unknownTime': 'Hora desconocida',
    'common.yes': 'Si',
    'common.no': 'No',
    'common.cancel': 'Cancelar',
    'community.community': 'Comunidad',
    'community.entitlements': 'Derechos',
    'community.linked': 'Vinculados',
    'community.listings': 'Listados',
    'community.loading': 'Cargando comunidad...',
    'community.createListing': 'Crear listado',
    'community.createPhrasePack': 'Crear frases',
    'community.description': 'Descripcion',
    'community.listingTitle': 'Titulo del listado',
    'community.phrasePackName': 'Nombre del paquete',
    'community.phrasePacks': 'Frases',
    'community.phrases': 'Frases',
    'community.priceUsd': 'Precio USD',
    'community.redeem': 'Canjear',
    'community.redeemCode': 'Canjear codigo',
    'community.referral': 'Referido',
    'community.referralCode': 'Codigo referido',
    'community.rewards': 'Recompensas',
    'community.save': 'Guardar',
    'control.status': 'Estado',
    'checkout.processing': 'Procesando pago...',
    'checkout.redirecting': 'Pago procesado. Redirigiendo...',
    'console.activityEmpty': 'Sin actividad del bot.',
    'console.blocksNearby': 'Bloques cercanos',
    'console.botPosition': 'Posicion del bot',
    'console.chatControl': 'Activar control por chat',
    'console.coordinates': 'Ingresa coordenadas',
    'console.follow': 'Seguir',
    'console.go': 'Ir',
    'console.inventory': 'Inventario',
    'console.moveTo': 'Mover a',
    'console.movingTo': 'Moviendo a',
    'console.placed': 'Colocado',
    'console.reachedGoal': 'Objetivo alcanzado en',
    'console.stop': 'Parar',
    'launch.botName': 'Nombre del bot',
    'launch.botNameHelp': 'El nombre que aparecera en el juego.',
    'launch.commanderUuid': 'Tu UUID de Minecraft',
    'launch.commanderUuidHelp': 'UUID del jugador que dara comandos.',
    'launch.launch': 'Lanzar',
    'launch.minecraftIp': 'IP del servidor Minecraft',
    'launch.minecraftIpHelp': 'Usa 127.0.0.1 por defecto para pruebas locales.',
    'launch.minecraftPort': 'Puerto del servidor Minecraft',
    'launch.minecraftPortHelp': 'Normalmente 25565 salvo que se cambie.',
    'launch.minecraftVersion': 'Version de Minecraft',
    'launch.minecraftVersionHelp': 'Debe coincidir con tu servidor.',
    'launch.title': 'Lanzar BuilderBot',
    'plan.acceptPolicies': 'Acepto los Terminos y la Politica de privacidad',
    'plan.adminDescription': 'Builds ilimitados, acceso completo',
    'plan.bestValue': 'Mejor valor',
    'plan.choosePlan': 'Bienvenido a BuilderBot. Elige tu plan',
    'plan.continueFree': 'Continuar gratis',
    'plan.freeDescription': 'Limitado a builds de 50 bloques',
    'plan.policyRequired': 'Acepta Terminos y Privacidad antes de elegir un plan.',
    'plan.proDescription': 'Builds de 2,000 bloques + chat IA',
    'plan.starterDescription': 'Builds de 500 bloques + plantillas',
    'plan.startCheckoutFailed': 'No se pudo iniciar checkout.',
    'plan.chooseFailed': 'No se pudo elegir el plan.',
    'plan.upgrade': 'Mejorar',
    'prompt.placeholder': 'Ingresa comando (ej. build a cube)...',
    'prompt.send': 'Enviar',
  },
  pt: {
    'admin.abuseEvents': 'Eventos de abuso',
    'admin.adminOperations': 'Operacoes admin',
    'admin.alerts': 'Alertas',
    'admin.failureRate': 'Taxa de falha',
    'admin.incidents': 'Incidentes',
    'admin.loading': 'Carregando dados admin...',
    'admin.margin': 'Margem',
    'admin.queue': 'Fila',
    'admin.sessions': 'Sessoes',
    'admin.security': 'Seguranca',
    'admin.tokenBurn': 'Custo tokens 1h',
    'app.dashboardTitle': 'Painel BuilderBot',
    'app.loading': 'Carregando...',
    'app.logout': 'Sair',
    'build.aiPatchPlans': 'Patches IA',
    'build.aiPlans': 'Planos IA',
    'build.attempts': 'Tentativas',
    'build.buildHistory': 'Historico',
    'build.loadingBuildDetails': 'Carregando detalhes...',
    'build.loadingBuilds': 'Carregando builds...',
    'build.localPlans': 'Planos locais',
    'build.localRatio': 'Ratio local',
    'build.noBuilds': 'Nenhum build registrado.',
    'build.replans': 'Replanos',
    'build.selectBuild': 'Selecione um build.',
    'build.source': 'Origem',
    'build.success': 'Sucesso',
    'build.successRate': 'Taxa sucesso',
    'build.totalBuilds': 'Builds totais',
    'build.aiCallsAvoided': 'IA evitada',
    'common.refresh': 'Atualizar',
    'common.unknown': 'Desconhecido',
    'common.unknownTime': 'Hora desconhecida',
    'common.yes': 'Sim',
    'common.no': 'Nao',
    'common.cancel': 'Cancelar',
    'community.community': 'Comunidade',
    'community.entitlements': 'Direitos',
    'community.linked': 'Vinculados',
    'community.listings': 'Listagens',
    'community.loading': 'Carregando comunidade...',
    'community.createListing': 'Criar listagem',
    'community.createPhrasePack': 'Criar frases',
    'community.description': 'Descricao',
    'community.listingTitle': 'Titulo da listagem',
    'community.phrasePackName': 'Nome do pacote',
    'community.phrasePacks': 'Frases',
    'community.phrases': 'Frases',
    'community.priceUsd': 'Preco USD',
    'community.redeem': 'Resgatar',
    'community.redeemCode': 'Resgatar codigo',
    'community.referral': 'Indicacao',
    'community.referralCode': 'Codigo indicacao',
    'community.rewards': 'Recompensas',
    'community.save': 'Salvar',
    'control.status': 'Status',
    'checkout.processing': 'Processando pagamento...',
    'checkout.redirecting': 'Pagamento processado. Redirecionando...',
    'console.activityEmpty': 'Sem atividade do bot.',
    'console.blocksNearby': 'Blocos proximos',
    'console.botPosition': 'Posicao do bot',
    'console.chatControl': 'Ativar controle por chat',
    'console.coordinates': 'Digite coordenadas',
    'console.follow': 'Seguir',
    'console.go': 'Ir',
    'console.inventory': 'Inventario',
    'console.moveTo': 'Mover para',
    'console.movingTo': 'Movendo para',
    'console.placed': 'Colocado',
    'console.reachedGoal': 'Objetivo alcancado em',
    'console.stop': 'Parar',
    'launch.botName': 'Nome do bot',
    'launch.botNameHelp': 'O nome que aparecera no jogo.',
    'launch.commanderUuid': 'Seu UUID do Minecraft',
    'launch.commanderUuidHelp': 'UUID do jogador que envia comandos.',
    'launch.launch': 'Iniciar',
    'launch.minecraftIp': 'IP do servidor Minecraft',
    'launch.minecraftIpHelp': 'Use 127.0.0.1 por padrao para testes locais.',
    'launch.minecraftPort': 'Porta do servidor Minecraft',
    'launch.minecraftPortHelp': 'Normalmente 25565 salvo alteracao.',
    'launch.minecraftVersion': 'Versao do Minecraft',
    'launch.minecraftVersionHelp': 'Deve corresponder ao servidor.',
    'launch.title': 'Iniciar BuilderBot',
    'plan.acceptPolicies': 'Aceito os Termos e a Politica de privacidade',
    'plan.adminDescription': 'Builds ilimitados, acesso completo',
    'plan.bestValue': 'Melhor valor',
    'plan.choosePlan': 'Bem-vindo ao BuilderBot. Escolha seu plano',
    'plan.continueFree': 'Continuar gratis',
    'plan.freeDescription': 'Limitado a builds de 50 blocos',
    'plan.policyRequired': 'Aceite Termos e Privacidade antes de escolher um plano.',
    'plan.proDescription': 'Builds de 2.000 blocos + chat IA',
    'plan.starterDescription': 'Builds de 500 blocos + modelos',
    'plan.startCheckoutFailed': 'Falha ao iniciar checkout.',
    'plan.chooseFailed': 'Falha ao escolher plano.',
    'plan.upgrade': 'Fazer upgrade',
    'prompt.placeholder': 'Digite comando (ex. build a cube)...',
    'prompt.send': 'Enviar',
  },
  fr: {
    'admin.abuseEvents': 'Evenements abus',
    'admin.adminOperations': 'Operations admin',
    'admin.alerts': 'Alertes',
    'admin.failureRate': 'Taux echecs',
    'admin.incidents': 'Incidents',
    'admin.loading': 'Chargement admin...',
    'admin.margin': 'Marge',
    'admin.queue': 'File',
    'admin.sessions': 'Sessions',
    'admin.security': 'Securite',
    'admin.tokenBurn': 'Cout tokens 1h',
    'app.dashboardTitle': 'Tableau BuilderBot',
    'app.loading': 'Chargement...',
    'app.logout': 'Deconnexion',
    'build.aiPatchPlans': 'Patchs IA',
    'build.aiPlans': 'Plans IA',
    'build.attempts': 'Essais',
    'build.buildHistory': 'Historique',
    'build.loadingBuildDetails': 'Chargement details...',
    'build.loadingBuilds': 'Chargement builds...',
    'build.localPlans': 'Plans locaux',
    'build.localRatio': 'Ratio local',
    'build.noBuilds': 'Aucun build.',
    'build.replans': 'Replans',
    'build.selectBuild': 'Selectionnez un build.',
    'build.source': 'Source',
    'build.success': 'Succes',
    'build.successRate': 'Taux succes',
    'build.totalBuilds': 'Builds totaux',
    'build.aiCallsAvoided': 'IA evitee',
    'common.refresh': 'Actualiser',
    'common.unknown': 'Inconnu',
    'common.unknownTime': 'Heure inconnue',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.cancel': 'Annuler',
    'community.community': 'Communaute',
    'community.entitlements': 'Droits',
    'community.linked': 'Lies',
    'community.listings': 'Annonces',
    'community.loading': 'Chargement communaute...',
    'community.createListing': 'Creer annonce',
    'community.createPhrasePack': 'Creer phrases',
    'community.description': 'Description',
    'community.listingTitle': 'Titre annonce',
    'community.phrasePackName': 'Nom du pack',
    'community.phrasePacks': 'Phrases',
    'community.phrases': 'Phrases',
    'community.priceUsd': 'Prix USD',
    'community.redeem': 'Utiliser',
    'community.redeemCode': 'Utiliser code',
    'community.referral': 'Parrainage',
    'community.referralCode': 'Code parrainage',
    'community.rewards': 'Recompenses',
    'community.save': 'Enregistrer',
    'control.status': 'Statut',
    'checkout.processing': 'Traitement du paiement...',
    'checkout.redirecting': 'Paiement traite. Redirection...',
    'console.activityEmpty': 'Aucune activite du bot.',
    'console.blocksNearby': 'Blocs proches',
    'console.botPosition': 'Position du bot',
    'console.chatControl': 'Activer controle chat',
    'console.coordinates': 'Entrer les coordonnees',
    'console.follow': 'Suivre',
    'console.go': 'Aller',
    'console.inventory': 'Inventaire',
    'console.moveTo': 'Aller a',
    'console.movingTo': 'Deplacement vers',
    'console.placed': 'Place',
    'console.reachedGoal': 'Objectif atteint a',
    'console.stop': 'Stop',
    'launch.botName': 'Nom du bot',
    'launch.botNameHelp': 'Le nom affiche en jeu.',
    'launch.commanderUuid': 'Votre UUID Minecraft',
    'launch.commanderUuidHelp': 'UUID du joueur qui envoie les commandes.',
    'launch.launch': 'Lancer',
    'launch.minecraftIp': 'IP du serveur Minecraft',
    'launch.minecraftIpHelp': '127.0.0.1 par defaut pour les tests locaux.',
    'launch.minecraftPort': 'Port du serveur Minecraft',
    'launch.minecraftPortHelp': 'Generalement 25565 sauf changement.',
    'launch.minecraftVersion': 'Version Minecraft',
    'launch.minecraftVersionHelp': 'Doit correspondre au serveur.',
    'launch.title': 'Lancer BuilderBot',
    'plan.acceptPolicies': 'J accepte les Conditions et la politique de confidentialite',
    'plan.adminDescription': 'Builds illimites, acces complet',
    'plan.bestValue': 'Meilleure offre',
    'plan.choosePlan': 'Bienvenue sur BuilderBot. Choisissez votre plan',
    'plan.continueFree': 'Continuer gratuit',
    'plan.freeDescription': 'Limite aux builds de 50 blocs',
    'plan.policyRequired': 'Acceptez Conditions et Confidentialite avant de choisir un plan.',
    'plan.proDescription': 'Builds de 2 000 blocs + chat IA',
    'plan.starterDescription': 'Builds de 500 blocs + modeles',
    'plan.startCheckoutFailed': 'Impossible de demarrer le checkout.',
    'plan.chooseFailed': 'Impossible de choisir le plan.',
    'plan.upgrade': 'Mettre a niveau',
    'prompt.placeholder': 'Commande (ex. build a cube)...',
    'prompt.send': 'Envoyer',
  },
};

const LocalizationContext = createContext({
  locale: 'en',
  supportedLocales: ['en'],
  setLocale: () => {},
  t: (key) => STRINGS.en[key] || key,
});

export function LocalizationProvider({ children }) {
  const [locale, setLocaleState] = useState(() => window.localStorage?.getItem('builderbot.locale') || 'en');
  const [supportedLocales, setSupportedLocales] = useState(['en']);

  useEffect(() => {
    let mounted = true;
    fetch('/api/config/localization')
      .then((response) => response.ok ? response.json() : null)
      .then((config) => {
        if (!mounted || !Array.isArray(config?.supportedLocales)) {
          return;
        }

        setSupportedLocales(config.supportedLocales);
        if (!config.supportedLocales.includes(locale)) {
          setLocaleState(config.defaultLocale || 'en');
        }
      })
      .catch(() => {});

    return () => {
      mounted = false;
    };
  }, [locale]);

  const setLocale = (nextLocale) => {
    const resolvedLocale = supportedLocales.includes(nextLocale) ? nextLocale : 'en';
    window.localStorage?.setItem('builderbot.locale', resolvedLocale);
    setLocaleState(resolvedLocale);
  };

  const value = useMemo(() => ({
    locale,
    supportedLocales,
    setLocale,
    t(key) {
      return STRINGS[locale]?.[key] || STRINGS.en[key] || key;
    },
  }), [locale, supportedLocales]);

  return (
    <LocalizationContext.Provider value={value}>
      {children}
    </LocalizationContext.Provider>
  );
}

export function useLocalization() {
  return useContext(LocalizationContext);
}
