// ai-agent.js
import 'dotenv/config.js';
import { OpenAI } from 'openai';
import WebSocket from 'ws';
import { offsetStructure } from '../shared-utils/offsetStructure.js';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// 🛰️ Get bot's live position
function getBotPosition() {
  return new Promise((resolve, reject) => {
    const ws = new WebSocket('ws://localhost:3001');

    ws.on('open', () => {
      ws.send(JSON.stringify({ type: 'get_position' }));
    });

    ws.on('message', (message) => {
      const data = JSON.parse(message);
      if (data.type === 'bot_position') {
        ws.close();
        resolve(data.position);
      }
    });

    ws.on('error', reject);
  });
}

function getInventory() {
  return new Promise((resolve, reject) => {
    const ws = new WebSocket('ws://localhost:3001');
    ws.on('open', () => {
      ws.send(JSON.stringify({ type: 'get_inventory' }));
    });
    ws.on('message', (message) => {
      const data = JSON.parse(message);
      if (data.type === 'bot_inventory') {
        ws.close();
        resolve(data.items);
      }
    });
    ws.on('error', reject);
  });
}

function getNearbyBlocks() {
  return new Promise((resolve, reject) => {
    const ws = new WebSocket('ws://localhost:3001');
    ws.on('open', () => {
      ws.send(JSON.stringify({ type: 'get_nearby_blocks' }));
    });
    ws.on('message', (message) => {
      const data = JSON.parse(message);
      if (data.type === 'nearby_blocks') {
        ws.close();
        resolve(data.blocks);
      }
    });
    ws.on('error', reject);
  });
}

// 🧠 Ask ChatGPT for block structure
async function getAICommand() {
  const chat = await openai.chat.completions.create({
    model: 'gpt-4',
    messages: [
      {
        role: 'system',
        content: `You are a Minecraft build AI.
          Return only a raw JSON array of blocks like:
          [
            { "x": 0, "y": 0, "z": 0, "block": "cobblestone" },
            { "x": 0, "y": 1, "z": 0, "block": "cobblestone" }
          ]
          All positions must be relative to origin (0,0,0). Do NOT include quotes, explanations, or markdown.`,
      },
      {
        role: 'user',
        content: 'Build a 10x10 house with, torches, a door, and a bed inside.',
      },
    ],
  });

  return chat.choices[0].message.content.trim();
}

// 📤 Send to bot
function sendToBot(structure) {
  const ws = new WebSocket('ws://localhost:3001');
  ws.on('open', () => {
    ws.send(JSON.stringify(structure));
    console.log(`✅ Sent ${structure.length} blocks to bot.`);
    ws.close();
  });
  ws.on('error', (err) => {
    console.error('❌ WebSocket error:', err.message);
  });
}

// 🚀 Main flow
async function main() {
  try {
    const [botPos, inventory, nearbyBlocks] = await Promise.all([
      getBotPosition(),
      getInventory(),
      getNearbyBlocks()
    ]);

    console.log('📍 Position:', botPos);
    console.log('🎒 Inventory:', inventory);
    console.log('🧱 Nearby Blocks:', nearbyBlocks.length);

    const context = { position: botPos, inventory, nearbyBlocks };

    // Local parsing via your custom function
    const { parsePrompt } = await import('../../packages/prompt-parser/index.js');

    const userPrompt = process.argv.slice(2).join(' ') || 'build a 3x3 stone floor';
    const steps = parsePrompt(userPrompt, context);

    if (!Array.isArray(steps) || steps.length === 0) {
      console.warn('⚠️ No steps generated by parser');
      return;
    }

    const adjustedSteps = offsetStructure(steps, botPos, { x: 2, y: -1, z: 2 });
    sendToBot(adjustedSteps);
  } catch (err) {
    console.error('❌ Error:', err.message);
  }
}

export default async function runAgent(prompt = 'build a 3x3 stone floor') {
  try {
    const [botPos, inventory, nearbyBlocks] = await Promise.all([
      getBotPosition(),
      getInventory(),
      getNearbyBlocks()
    ]);

    const context = { position: botPos, inventory, nearbyBlocks };
    const { parsePrompt } = await import('../../packages/prompt-parser/index.js');

    console.log('🧠 Parsing prompt with context:', {
      prompt,
      context
    });

    const steps = parsePrompt(prompt, context);

    console.log('🛠️ Generated steps:', steps);

    if (!Array.isArray(steps) || steps.length === 0) {
      console.warn('⚠️ No steps generated by parser');
      return;
    }

    const adjustedSteps = offsetStructure(steps, botPos, { x: 2, y: 1, z: 2 });
    sendToBot(adjustedSteps);
  } catch (err) {
    console.error('❌ Agent error:', err.message);
  }
}